MapsActivity is almost finished: now GPS position seems to work. Created StudyPlanActivity where to elaborate the algorithm for searching free classrooms. Added support to RxAndroid (RxJava) and some minor changes to the code. Bug fixes. One bug in details: Fixed app crash adding this line in the app Manifest: <uses-library android:name="org.apache.http.legacy" android:required="false"/> Error message: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion DOCS at: https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library